main/urls.py
# coding: utf-8
from django.conf.urls import  url
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^out/$', views.out, name='out'),
    url(r'^weather/$', views.weather, name='weather'),
       
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


mysite/urls.py
# coding: utf-8
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main import views
from tts.views import *


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^polis/', include('polis.urls', namespace='polis')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^tts/', tts_play),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polis/urls.py
from django.conf.urls import  url
from polis import views


urlpatterns = [
    # /polis/
    url(r'^$', views.index, name='index'),

    # /plis/5
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),

    # /plis/5/results/
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),

    # /plis/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

]


polis/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description= 'Published recently?'




class Choice(models.Model):
    question  = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polis/views.py
# -*- coding: utf-8 -*- 

from django.http import HttpResponse
from polis.models import Question
from django.http import Http404

from django.shortcuts import get_object_or_404, render
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #template = loader.get_template('polis/index.html')
    print(latest_question_list)
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polis/index.html', context)

    #return HttpResponse("hello, world. your're at the polis index.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polis/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
	

polis/templates/polis/detail.html
{% extends 'layout.html' %}
{% block body %}
<h1>{{ question.question_text }}</h1>
<div class="container">
	<div class="row centered mt mb">
	

{% if question %}
 {% for choice in question.choice_set.all %}
	<div class="col-lg-4 col-md-4 col-sm-4 gallery">
		{{ choice.choice_text }}
	</div>
{% endfor %}
	
{% else %}
<div class="col-lg-4 col-md-4 col-sm-4 gallery">
		No polls are available.
</div>

{% endif %}

	
	
	
	</div>
</div>
{% endblock %}

polis/templates/polis/index.html
{% extends 'layout.html' %}
{% block body %}
<div class="container">
	<div class="row centered mt mb">
	

{% if latest_question_list %}
{% for question in latest_question_list %}
	<div class="col-lg-4 col-md-4 col-sm-4 gallery">
		<a href="{% url 'polis:detail' question.id %}">{{ question.question_text }}</a>
	</div>
{% endfor %}
	
{% else %}
<div class="col-lg-4 col-md-4 col-sm-4 gallery">
		No polls are available.
</div>

{% endif %}

	
	
	
	</div>
</div>
{% endblock %}