main/urls.py
# coding: utf-8
from django.conf.urls import  url
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^out/$', views.out, name='out'),
    url(r'^weather/$', views.weather, name='weather'),
       
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


mysite/urls.py
# coding: utf-8
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main import views
from tts.views import *


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^polis/', include('polis.urls', namespace='polis')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^tts/', tts_play),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
# coding: utf-8
from django.conf.urls import  url
from photo import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #photo 출력    
    url(r'^photo/(?P<photo_id>\d+)$',views.single_photo, name='view_single_photo'),
    
    #photo upload
    url(r'^photo/upload/$',views.new_photo, name='new_photo'),
    
    url(r'^out/$', views.out, name='out'),   
    url(r'^cam/$', views.open, name='cam'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


photo/models.py
# coding: utf-8

from __future__ import unicode_literals

from django.db import models
#from django.urls.base import reverse_lazy

# Create your models here.
class Photo(models.Model):
    image_file = models.ImageField(upload_to='%Y/%m/%d')
    filtered_image_file = models.ImageField(upload_to='static_files/uploaded/%Y/%m/%d')
    description = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    def delete(self, *args, **kwargs):
        self.image_file.delete()
        self.filtered_image_file.delete()
        super(Photo, self).delete(*args, **kwargs)
    '''    
    def get_absolute_url(self):
        return reverse_lazy('view_single_photo', kwargs={'photo_id':self.id})
        
    '''
        

photo/forms.py
# coding: utf-8
from __future__ import unicode_literals

from django import forms

from photo.models import Photo

class PhotoEditForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ('filtered_image_file', )

photo/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Photo
from photo.forms import PhotoEditForm
from photo.method import shutdown, pingChk, openCam
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
# Create your views here.

def single_photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    print(photo.image_file.url)
    response_text = '<p>{photo_id}번 ... {photo_id}번 사진출력</p>'
    response_text += '<p>{photo_url}</p>'
    response_text += '<p><img src="{photo_url}" width=200 height=200/></p>'
    return HttpResponse(response_text.format(
                                            photo_id=photo_id,
                                            photo_url=photo.image_file.url))
    
def new_photo(request):
    if request.method == "GET":        
        edit_form = PhotoEditForm()
    elif request.method == "POST":
        edit_form = PhotoEditForm(request.POST, request.FILES)
        '''
        if edit_form.is_valid():
            new_photo = edit_form.save()
            
            return redirect(new_photo.get_absolute_url())
        '''
    
    return render(request, 'new_photo.html', {
                                                'form':edit_form,})
    
def index(request):
    response_text = ""
    latest_photo_list = Photo.objects.order_by('-created_at')[:5]
    if latest_photo_list.count()>0:        
        for photo in latest_photo_list:  
            response_text += '<p><img src="' + photo.image_file.url + '" width=200 height=200/></p>'   
        print(response_text)    
        
    chk = "N"
    ip = '172.30.1.45'
    res = pingChk(ip)
    if res==0:
        print('up')
        chk = "Y"
    else:
        print('down')        
    
    
    context = {'latest_photo_list': latest_photo_list,
               'response_text': response_text,
               'chk':chk,}
    return render(request, 'photo/index.html', context)


def out(request):
    print("enter")
    ip = '172.30.1.45'
    res = pingChk(ip)
    
    if res==0:
        print('up')
        shutdown(ip)
    else:
        print('down')        
        
        
    return HttpResponseRedirect(reverse('photo:index'))
    
#test
def open(request):
    print("cam enter")
    openCam()
    return HttpResponseRedirect(reverse('photo:index'))
    

photo/templates/photo/index.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block body %}
    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">INSTANT</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="#works">Works</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


	<div id="headerwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<h4>집 page</h4>
					<h1>한호준</h1>
					<h4>WEB DESIGNER, DEVELOPER & GAME ADDICT</h4>
				</div>
			</div><! --/row -->
	    </div> <!-- /container -->
	</div><! --/headerwrap -->
	
	<section id="works"></section>
	<div class="container">
		<div class="row centered mt mb">
			<h1>목록</h1>
			{% if chk == 'Y' %}
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="{% url 'photo:out' %}"><img src="{% static 'img/com.png' %}" class="img-responsive"></a>
			</div>
			{% endif %}
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="work.html"><img src="{% static 'img/portfolio/folio02.png' %}" class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="work.html"><img src="{% static 'img/portfolio/folio03.png' %}" class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="work.html"><img src="{% static 'img/portfolio/folio04.png' %}" class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="work.html"><img src="{% static 'img/portfolio/folio05.png' %}" class="img-responsive"></a>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="work.html"><img src="{% static 'img/portfolio/folio06.png' %}" class="img-responsive"></a>
			</div>
		</div><! --/row -->
	</div><! --/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><! --/row -->
		</div><! --/container -->
	</div><! --/social -->
{% endblock %}






photo/templates/photo/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block page_title %}Pystagram{% endblock %}</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>

photo/templates/photo/new_photo.html
{% extends 'layout.html' %}
{% block content %}
<form method="post" action="{% url 'photo:new_photo' %}" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	
	<p><input type="submit"/></p>
</form>
{% endblock %}