main/urls.py
# coding: utf-8
from django.conf.urls import  url
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^out/$', views.out, name='out'),
    url(r'^weather/$', views.weather, name='weather'),
       
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


mysite/urls.py
# coding: utf-8
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main import views
from tts.views import *


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^polis/', include('polis.urls', namespace='polis')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^tts/', tts_play),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Main(models.Model):
    title_text1 = models.CharField(max_length=20, blank=True)
    title_text2 = models.CharField(max_length=20, blank=True)
    title_text3 = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    def delete(self, *args, **kwargs):
        super(Main, self).delete(*args, **kwargs)
   
class MainBanner(models.Model):
    main  = models.ForeignKey(Main)
    banner_text = models.CharField(max_length=200)
    banner_img = models.ImageField(upload_to='main/banner')

    def __str__(self):
        return self.banner_text
    

main/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render
from main.models import Main, MainBanner
from django.http import Http404
from django.shortcuts import get_object_or_404
from gc import get_objects
import time
import os


from main.method import shutdown, pingChk
# Create your views here.
def index(request):
    main = Main.objects
    main_id = unicode(str(main.get().id))
    main_banner = MainBanner.objects.filter(main_id = main_id)
    #template = loader.get_template('polis/index.html')
    print(main,main_banner)
    
    chk = "N"
    ip = '172.30.1.45'
    res = pingChk(ip)
    if res==0:
        print('up')
        chk = "Y"
    else:
        print('down')      
        
        
    context = {'main': main.get(),
               'main_banner': main_banner,
               'chk':chk,}
    return render(request, 'main/index.html', context)



def out(request):
    print("enter")
    ip = '172.30.1.45'
    res = pingChk(ip)
    
    if res==0:
        print('up')
        shutdown(ip)
        time.sleep(5)
    else:
        print('down')        
        
        
    return HttpResponseRedirect(reverse('photo:index'))

def weather(request):
    
    
    os.system('python3 /home/pi/python_test/센서_대기/TOUCH_바로실행.py')
    return HttpResponseRedirect(reverse('photo:index'))

main/templates/main/index.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block body %}
    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">INSTANT</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="#works">Works</a></li>
            <li><a href="admin/">Admin</a></li>
            
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


	<div id="headerwrap">
	    <div class="container">
			<div class="row">
				<div class="col-lg-6 col-lg-offset-3">
					<h4>{{main.title_text1}}</h4>
					<h1>{{main.title_text2}}</h1>
					<h4>{{main.title_text3}}</h4>
				</div>
			</div><!--/row -->
	    </div> <!-- /container -->
	</div><!--/headerwrap -->
	
	<section id="works"></section>
	<div class="container">
		<div class="row centered mt mb">
			<h1>목록</h1>
			{% if chk == 'Y' %}
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="{% url 'main:out' %}"><img src="{% static 'img/com.png' %}" class="img-responsive"></a>
			</div>
			{% endif %}			
			<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="{% url 'main:weather' %}"><img src="{% static 'img/weather.png' %}" class="img-responsive"></a>
			</div>
		    {% for banner in main_banner %}
       	 	<div class="col-lg-4 col-md-4 col-sm-4 gallery">
				<a href="#"><img src="{{ banner.banner_img.url }}" class="img-responsive"></a>
			</div>		
		    {% endfor %}
		</div><!--/row -->
	</div><!--/container -->
	
	<div id="social">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-dribbble"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-twitter"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-linkedin"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-instagram"></i></a>
				</div>
				<div class="col-lg-2">
					<a href="#"><i class="fa fa-tumblr"></i></a>
				</div>
			
			</div><!--/row -->
		</div><!--/container -->
	</div><!--/social -->
{% endblock %}


